// Auth
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// Patients
export const GET_PATIENTS = 'GET_PATIENTS';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const ADD_PATIENT = 'ADD_PATIENT';
export const PATIENTS_LOADING = 'PATIENTS_LOADING';
export const GET_HISTORY = 'GET_HISTORY';
export const GET_ORDER = 'GET_ORDER';
export const GET_ALL_IMAGES = 'GET_ALL_IMAGES';
export const IMAGES_UPLOAD = 'IMAGES_UPLOAD';

// All users
export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING';

//Employes
export const GET_EMPLOYERS = 'GET_EMPLOYES';
export const GET_ONE_EMPLOYEE = 'GET_ONE_EMPLOYEE';
export const ADD_EMPLOYERS = 'ADD_EMPLOYES';
export const EDIT_EMPLOYERS = 'EDIT_EMPLOYES';
export const EMPLOYERS_LOADING = 'EMPLOYES_LOADING';
export const GET_SELECT = 'GET_SELECT';
export const ERROR_ADD = 'ERROR_ADD';


// Livetapes
export const GET_LIVETAPE = 'GET_LIVETAPE';
export const LIVETAPE_LOADING = 'LIVETAPE_LOADING';

// Shedule
export const SHEDULE_GET = "SHEDULE_GET";
export const SHEDULE_LOADING = "SHEDULE_LOADING";
export const SHEDULE_LIVE_GET = "SHEDULE_LIVE_GET";
export const CALENDAR_GET = "CALENDAR_GET";
export const CALENDAR_LOADING = "CALENDAR_LOADING";
export const BRANCHES_GET = "BRANCHES_GET";
export const BRANCHES_LOADING = "BRANCHES_LOADING";
export const FILTER_GET = "FILTER_GET";
export const FILTER_LOADING = "FILTER_LOADING";
// export const DOCTORS_SCHEDULE_GET = "DOCTORS_SCHEDULE_GET";
// export const DOCTORS_SCHEDULE_LOADING = "DOCTORS_SCHEDULE_LOADING";

//Prices
export const GET_PRICES = 'GET_PRICES';
export const ADD_CATEGORY_PRICE = 'ADD_CATEGORY_PRICE';
export const ADD_PRODUCT_PRICE = 'ADD_PRODUCT_PRICE';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_CATEGORY = 'DELETE_PRODUCT';
export const PRICES_LOADING = 'PRICES_LOADING';

//Materials
export const GET_ALL_MATERIALS = 'GET_PRICES';
export const MATERIALS_LOADING = 'PRICES_LOADING';
export const ADD_CATEGORY_MATERIALS = 'ADD_CATEGORY_MATERIALS';
export const DELETE_CATEGORY_MATERIAL = 'DELETE_CATEGORY_MATERIAL';
export const EDIT_CATEGORY_MATERIALS = 'EDIT_CATEGORY_MATERIALS';
export const ADD_MATERIAL = 'ADD_MATERIAL';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const GET_SELECT_PROVIDER = 'GET_SELECT_PROVIDER';
export const CREATE_INVOICE = 'CREATE_INVOICE';
export const GET_SELECT_CABINET_INVOICES = 'GET_SELECT_CABINET_INVOICES';
export const CREATE_CABINET_INVOICE = 'CREATE_CABINET_INVOICE';
export const GET_STORAGE_ITEM = 'GET_STORAGE_ITEM';
export const GET_QUANTITY = 'GET_QUANTITY';
export const EDIT_MATERIALS = 'EDIT_MATERIALS';
export const GET_CABINET_INVOICES = 'GET_CABINET_INVOICES';
export const FILTER_JOURNAL = 'FILTER_JOURNAL';

//Settings
export const GET_SETTINGS_BRANCHES = 'GET_SETTINGS_BRANCHES';
export const CREATE_SETTINGS_BRANCH = 'CREATE_SETTINGS_BRANCH';
export const SETTINGS_BRANCHES_LOADING = 'SETTINGS_BRANCHES_LOADING';
export const CREATE_BRANCH_CABINET = 'CREATE_BRANCH_CABINET';

//CRM
export const CRM_LOADING = 'CRM_LOADING';
export const GET_RECORDS_CRM = 'GET_RECORDS_CRM';
export const GET_TASKS_CALLING = 'GET_TASKS_CALLING';
export const ADD_TASK = 'ADD_TASK';
export const GET_ALL_TASKS = 'GET_ALL_TASKS';
export const GET_SELECT_FILTER = 'GET_SELECT_FILTER';
export const GET_FILTER_TASKS = 'GET_FILTER_TASKS';
export const GET_PAGE_TASKS = 'GET_PAGE_TASKS';
export const GET_WAITING_LISTS = 'GET_WAITING_LISTS';
export const ADD_WAITING_LIST = 'ADD_WAITING_LIST';
export const GET_WAITING_CATS = 'GET_WAITING_CATS';

//cashBox
export const GET_DEVICES = 'GET_DEVICES';
export const CASHBOX_LOADING = 'CASHBOX_LOADING';

// Doctors schedule
export const DOCTORS_SCHEDULE_FILTER = "DOCTORS_SCHEDULE_FILTER";
export const DOCTORS_SCHEDULE_FILTER_LOADING = "DOCTORS_SCHEDULE_FILTER_LOADING";
export const DOCTORS_SCHEDULE_GET = "DOCTORS_SCHEDULE_GET";
export const DOCTORS_SCHEDULE_LOADING = "DOCTORS_SCHEDULE_LOADING";
